version: "3"
services:
  teeworlds-server:
    image: audeldiaz/teeworlds-srv:0.7.5
    ports:
      - "8303:8303/udp"
    volumes:
      - data:/src/app/data
      - ./config:/src/app/config:ro

volumes:
  data: